### ISSUE TITLE
Cannot install on ES2.0 (or 2.1)

### ISSUE THREAD

**Issue by jackeavans** [jlinn/elasticsearch-analysis-url#1]
On a fresh install of ES2.0, the command 

    bin/plugin install analysis-url --url https://github.com/jlinn/elasticsearch-analysis-url/releases/download/v2.1.0/elasticsearch-analysis-url-2.1.0.zip

does not work anymore. I changed it for 

    bin/plugin install https://github.com/jlinn/elasticsearch-analysis-url/releases/download/v2.1.0/elasticsearch-analysis-url-2.1.0.zip

which is the correct syntax for ES2.0. But now, ES complains about a missing "plugin-descriptor.properties" file in the plugin (this file is mandatory on ES2.0).

Am I doing something wrong here?

Btw, awesome plugin! I had been scratching my head for days about this issue and almost implemented it source-side (doing the "right" tokenization before putting the document in ES), which isn't nearly as elegant as your plugin.

**Comment by jackeavans** [comment]
Adding [this file](https://github.com/jlinn/elasticsearch-analysis-url/files/73337/plugin-descriptor.properties.txt) (without the txt extension) to the zip release solved the problem. Unfortunately, the plugin doesn't run for ES2.1. It installs fine, but at runtime throws `IndexCreationException[failed to create index]; nested: IllegalStateException[[index.version.created] is not present in the index settings for index with uuid: [null]];`

**Comment by jlinn** [comment]
Thanks for the kind words.  I did some digging before writing this plugin, and I was pretty surprised that nothing like it already existed.

Thanks for letting me know about this.  I'll take a look at it this evening.

**Comment by jlinn** [comment]
Ok, version [2.1.1](https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v2.1.1) should fix this issue.

**Comment by jackeavans** [comment]
Awesome! I was about to send you a PR as I managed to make it work after a few hours of maven hell.
Anyway, thanks for the quick commit (and the plugin).
