### ISSUE TITLE
ES 2.4.3?

### ISSUE THREAD

**Issue by mathewmeconry** [jlinn/elasticsearch-analysis-url#16]
Could you please build a package for es 2.4.3?

**Comment by jlinn** [comment]
No problem.  [v2.4.3.0](https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v2.4.3.0) should work for you.

**Comment by mathewmeconry** [comment]
unfortunately the plugin binary of elastic doesn't allow me to install it because the compatibility isn't listed in your definition file

**Comment by jlinn** [comment]
That's odd.  I was able to install it on ES v2.4.3 without any issues.  Would you mind sharing the error message you're seeing?

**Comment by mathewmeconry** [comment]
I got this error:
`ERROR: Plugin [analysis-url] is incompatible with Elasticsearch [2.4.3]. Was designed for version [2.4.1]`

But I saw now there is a explicit version for 2.4.3. Have you added this recently?

**Comment by jlinn** [comment]
Ah.  Yes, I added that version 10 days ago.  Give [v2.3.4.0](https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v2.4.3.0) a try.  It should work.

**Comment by mathewmeconry** [comment]
Yes 2.3.4.0 worked
