### ISSUE TITLE
Enhance the token filter with "pass through" semantics

### ISSUE THREAD

**Issue by consulthys** [jlinn/elasticsearch-analysis-url#2]
The token filter provided by this plugin is super useful on fields which only contain an URL. It would be even more useful if we could use it to analyze fields containing arbitrary text possibly with URLs in them (think user comments).

I suggest to add another option called `pass_through` to the URL Token Filter. If this option is set to `true`, the token filter would just pass the token through without any modifications instead of just rejecting the document. And `allow_malformed` would need to be `true`, I guess.

This would allow to use the `url` token filter and analyze a free-text user comment with URLs in them. For instance: the text `bla bla http://www.google.com bla bla` would be tokenized into (using `whitespace` tokenizer):
 * bla (not a URL, just pass through)
 * bla (not a URL, just pass through)
 * www.google.com
 * bla (not a URL, just pass through)
 * bla (not a URL, just pass through)

Even better, would be to also have the option to set `tokenize_host` on the token filter, so that the host would be further tokenized into:
 * www.google.com
 * google.com
 * com

Currently, if the `url` token filter is set up with `part: whole` and `allow_malformed: true`, it will stop tokenizing after the first token `bla` in my example above. The new option I'm suggesting would just tell the token filter to keep going with the other tokens.

**Comment by jlinn** [comment]
Great suggestion.  I should have some time to work on it this weekend.

**Comment by consulthys** [comment]
Awesome! Thank you for this great and promising plugin, I'm eager to leverage it on many use cases as soon as this is implemented! Thanks again.

**Comment by jlinn** [comment]
I've released [v2.2.0|https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v2.2.0], which includes the `passthrough` option.  Let me know if you encounter any issues with it.

**Comment by consulthys** [comment]
You rock!! It works [very well](http://stackoverflow.com/a/34986008/4604579). Thanks a lot!!

**Comment by jlinn** [comment]
Awesome.  Glad to hear it.
