### ISSUE TITLE
Having issue with index creation and settings on 2.1.1

### ISSUE THREAD

**Issue by cambri** [jlinn/elasticsearch-analysis-url#4]
For anyone receiving an error like this after installing plugin, make sure to restart your elasticsearch service :-)

{"error":{"root_cause":[{"type":"index_creation_exception","reason":"failed to create index"}],"type":"illegal_argument_exception","reason":"Unknown Tokenizer type [url] for [url_host]"},"status":400}

**Comment by jlinn** [comment]
Ah, ok.  Yes, Elasticsearch needs to be restarted after installing any JVM plugins.  I should probably update the readme with that information.  Did restarting the node resolve your issue?

**Comment by povilasb** [comment]
Yep, it helped for me :)

**Comment by jlinn** [comment]
Excellent.
