### ISSUE TITLE
Elasticsearch 2.3.3 build

### ISSUE THREAD

**Issue by skyshard** [jlinn/elasticsearch-analysis-url#6]
A bugfix release was just announced by elastic: https://www.elastic.co/blog/elasticsearch-2-3-3-released

Would it be possible to publish another release of this plugin? Thanks!

**Comment by jlinn** [comment]
No problem.  The new release can be found [here](https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v2.3.3).

**Comment by skyshard** [comment]
thanks!
