### ISSUE TITLE
add option "ignore_protocol"

### ISSUE THREAD

**Issue by wuyadong** [jlinn/elasticsearch-analysis-url#9]
Could add an option "ignore_protocol" for tokenizer?

Default is false.  If true, no protocol in the url still can be tokenized, like 'foo.bar.com/baz.html'

**Comment by jlinn** [comment]
Rather than add special options to ignore specific parts of a malformed URL, I'd like to enhance tokenization capabilities for all malformed URLs.  

What version of Elasticsearch are you using?  Assuming the changes I make work for you, I'll merge them into the appropriate plugin version.

**Comment by wuyadong** [comment]
@jlinn Thanks a lot. I'm using the 2.3.3 version.

**Comment by jlinn** [comment]
I've released [version 2.3.3.2](https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v2.3.3.2) with the `parse_malformed` option.  Hopefully that works for you.

**Comment by wuyadong** [comment]
@jlinn I just have test version 2.3.3.2.  
It seems not working.

```
PUT /url_test/
{
  "settings": {
      "analysis": {
          "analyzer": {
              "url_analyzer": {
                  "filter": "lowercase",
                  "tokenizer": "url_tokenizer",
                  "type": "custom"
              }
          },
          "tokenizer": {
                "url_tokenizer": {
                  "type": "url",
                   "allow_malformed": "true",
                   "tokenize_malformed": "true"
              }
          }
      }
  }
}
```

```
POST /url_test/_analyze?analyzer=url_analyzer
{
  "text" : "foo.bar.com/baz.html/query?a=1"
}

result:
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[Random][ip:9300][indices:admin/analyze[s]]"
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```

**Comment by wuyadong** [comment]
I continue test, some time the type:whole is duplicated:
```
{
  "text" : "http://foo.bar.com"
}


{
  "tokens": [
    {
      "token": "http",
      "start_offset": 0,
      "end_offset": 4,
      "type": "protocol",
      "position": 0
    },
    {
      "token": "foo.bar.com",
      "start_offset": 7,
      "end_offset": 18,
      "type": "host",
      "position": 1
    },
    {
      "token": "bar.com",
      "start_offset": 11,
      "end_offset": 18,
      "type": "host",
      "position": 2
    },
    {
      "token": "com",
      "start_offset": 15,
      "end_offset": 18,
      "type": "host",
      "position": 3
    },
    {
      "token": "80",
      "start_offset": 0,
      "end_offset": 0,
      "type": "port",
      "position": 4
    },
    {
      "token": "http://foo.bar.com",  <---- duplicated below
      "start_offset": 0,
      "end_offset": 18,
      "type": "whole",
      "position": 5
    },
    {
      "token": "foo.bar.com:80",
      "start_offset": 0,
      "end_offset": 0,
      "type": "whole",
      "position": 6
    },
    {
      "token": "http://foo.bar.com",   <---- same with position: 5
      "start_offset": 0,
      "end_offset": 18,
      "type": "whole",
      "position": 7
    }
  ]
}

```

**Comment by wuyadong** [comment]
And I have some confusions as below:

1. The `whole` part should be at first position, so if we search the *whole URL* , it will match the `whole` first.
2. Like this `foo.bar.com:80`, host with port should not be `whole`?

**Comment by jlinn** [comment]
Thanks for the quick feedback.  I've corrected those issues in the attached snapshot release.
[elasticsearch-analysis-url-2.3.3.3-SNAPSHOT.zip](https://github.com/jlinn/elasticsearch-analysis-url/files/334373/elasticsearch-analysis-url-2.3.3.3-SNAPSHOT.zip)

**Comment by wuyadong** [comment]
Oh, you are so fast!  Thanks. 

Now, the ``` "foo.bar.com/baz.html/query?a=1" ``` is return right.

I also tested below URLs:
```
"http://foo.bar.com"
"http://foo.bar.com/query?a=123"
"http://foo.bar.com/x.html/query?a=123"
```

The `whole` part not at the same position.
